name: E-Commerce Checkout & Payment System - backend

on:
  push:
    branches:
      - main
    paths:
      - 'task-02/customer-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: npm install, build, and test
        working-directory: ./task-02/customer-backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: task-02/customer-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2   
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DF1F76D631D74D2DA41502C552608A92 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39565B627B524265B7B17FEC6B95FDA7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C301A2C269094F249AFB5AE39E091112 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'customerapp-backend'
          slot-name: 'Production'
          package: .



          